### ISSUE TITLE
Key Repair Lens fails with MimirError:('java.lang.IllegalArgumentException: An unknown error occurred...',)

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/web-ui#148]
steps to repeat:

Create a dataset with two integer columns A and B

Create a key repair lens for any attribute:
~~~
MimirError:('java.lang.IllegalArgumentException: An unknown error occurred...',)
~~~

vizier log:

~~~
127.0.0.1 - - [12/Aug/2019 14:02:00] "POST /vizier-db/api/v1/projects/dfe3be1e/branches/276e12c4/head HTTP/1.1" 200 -
MimirAPI POST /api/v2/lens/create
{"materialize": false, "input": "LENS_PICKER1524413256", "humanReadableName": "PK", "params": ["B"], "type": "KEY_REPAIR"}
MimirAPI POST /api/v2/schema
{"query": "SELECT RID,A,B,C FROM LENS_KEY_REPAIR461969377;"}
MimirAPI POST /api/v2/query/data
{"input": "", "includeReasons": false, "includeUncertainty": false, "query": "SELECT RID FROM LENS_KEY_REPAIR461969377;"}
14:02:01.336 [qtp1141374626-388] ERROR mimir.MimirVizier$ - Error Querying Mimir -> CSV: SELECT RID FROM LENS_KEY_REPAIR461969377;
java.lang.IllegalArgumentException: Invalid JSON (9) for Type rowid
	at mimir.serialization.Json$.toPrimitive(Json.scala:498)
	at mimir.models.RepairKeyModel$$anonfun$1.apply(RepairKeyModel.scala:72)
	at mimir.models.RepairKeyModel$$anonfun$1.apply(RepairKeyModel.scala:72)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mimir.models.RepairKeyModel.getDomain(RepairKeyModel.scala:72)
	at mimir.models.RepairKeyModel.bestGuess(RepairKeyModel.scala:45)
	at mimir.ctables.vgterm.BestGuess.get(BestGuess.scala:23)
	at mimir.exec.EvalInlined$$anonfun$compileProc$1.apply(EvalInlined.scala:62)
	at mimir.exec.EvalInlined$$anonfun$compileProc$1.apply(EvalInlined.scala:62)
	at mimir.exec.EvalInlined$$anonfun$compilePassthrough$4.apply(EvalInlined.scala:285)
	at mimir.exec.EvalInlined$$anonfun$compileConditional$1.apply(EvalInlined.scala:88)
	at mimir.exec.EvalInlined$$anonfun$checkNull$1.apply(EvalInlined.scala:21)
	at mimir.exec.EvalInlined$$anonfun$checkNull$1.apply(EvalInlined.scala:20)
	at mimir.exec.result.LazyRow$$anonfun$tuple$1.apply(LazyRow.scala:14)
	at mimir.exec.result.LazyRow$$anonfun$tuple$1.apply(LazyRow.scala:14)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mimir.exec.result.LazyRow.tuple(LazyRow.scala:14)
	at mimir.MimirVizier$$anonfun$operCSVResults$1.apply(MimirVizier.scala:1177)
	at mimir.MimirVizier$$anonfun$operCSVResults$1.apply(MimirVizier.scala:1172)
	at mimir.Database.query(Database.scala:145)
	at mimir.Database.query(Database.scala:172)
	at mimir.MimirVizier$.operCSVResults(MimirVizier.scala:1172)
	at mimir.MimirVizier$$anonfun$26.apply(MimirVizier.scala:601)
	at mimir.MimirVizier$$anonfun$26.apply(MimirVizier.scala:589)
	at mimir.MimirVizier$.logTime(MimirVizier.scala:1345)
	at mimir.MimirVizier$.vistrailsQueryMimir(MimirVizier.scala:589)
	at mimir.MimirVizier$.vistrailsQueryMimir(MimirVizier.scala:584)
	at mimir.api.QueryMimirRequest.handle(Request.scala:332)
	at mimir.api.MimirVizierServlet.doPost(MimirAPI.scala:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:745)
14:02:01.337 [qtp1141374626-388] ERROR mimir.api.MimirVizierServlet - MimirAPI POST ERROR:
java.lang.IllegalArgumentException: Invalid JSON (9) for Type rowid
	at mimir.serialization.Json$.toPrimitive(Json.scala:498)
	at mimir.models.RepairKeyModel$$anonfun$1.apply(RepairKeyModel.scala:72)
	at mimir.models.RepairKeyModel$$anonfun$1.apply(RepairKeyModel.scala:72)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mimir.models.RepairKeyModel.getDomain(RepairKeyModel.scala:72)
	at mimir.models.RepairKeyModel.bestGuess(RepairKeyModel.scala:45)
	at mimir.ctables.vgterm.BestGuess.get(BestGuess.scala:23)
	at mimir.exec.EvalInlined$$anonfun$compileProc$1.apply(EvalInlined.scala:62)
	at mimir.exec.EvalInlined$$anonfun$compileProc$1.apply(EvalInlined.scala:62)
	at mimir.exec.EvalInlined$$anonfun$compilePassthrough$4.apply(EvalInlined.scala:285)
	at mimir.exec.EvalInlined$$anonfun$compileConditional$1.apply(EvalInlined.scala:88)
	at mimir.exec.EvalInlined$$anonfun$checkNull$1.apply(EvalInlined.scala:21)
	at mimir.exec.EvalInlined$$anonfun$checkNull$1.apply(EvalInlined.scala:20)
	at mimir.exec.result.LazyRow$$anonfun$tuple$1.apply(LazyRow.scala:14)
	at mimir.exec.result.LazyRow$$anonfun$tuple$1.apply(LazyRow.scala:14)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mimir.exec.result.LazyRow.tuple(LazyRow.scala:14)
	at mimir.MimirVizier$$anonfun$operCSVResults$1.apply(MimirVizier.scala:1177)
	at mimir.MimirVizier$$anonfun$operCSVResults$1.apply(MimirVizier.scala:1172)
	at mimir.Database.query(Database.scala:145)
	at mimir.Database.query(Database.scala:172)
	at mimir.MimirVizier$.operCSVResults(MimirVizier.scala:1172)
	at mimir.MimirVizier$$anonfun$26.apply(MimirVizier.scala:601)
	at mimir.MimirVizier$$anonfun$26.apply(MimirVizier.scala:589)
	at mimir.MimirVizier$.logTime(MimirVizier.scala:1345)
	at mimir.MimirVizier$.vistrailsQueryMimir(MimirVizier.scala:589)
	at mimir.MimirVizier$.vistrailsQueryMimir(MimirVizier.scala:584)
	at mimir.api.QueryMimirRequest.handle(Request.scala:332)
	at mimir.api.MimirVizierServlet.doPost(MimirAPI.scala:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:745)
127.0.0.1 - - [12/Aug/2019 14:02:01] "GET /vizier-db/api/v1/projects/dfe3be1e/branches/276e12c4/head/modules/49b83d86 HTTP/1.1" 200 -
127.0.0.1 - - [12/Aug/2019 14:02:01] "GET /vizier-db/api/v1/projects/dfe3be1e/branches/276e12c4/head HTTP/1.1" 200 -
~~~

**Comment by okennedy** [comment]
This is probably not an issue with Mimir v2, but let's check.

**Comment by okennedy** [comment]
Found a few other minor glitches that are now fixed.
