### ISSUE TITLE
Manual Column Insertions Fail with a Parse Error

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#184]
Reproduction Steps:
1. Load Any Dataset
2. Create and run a new insert column cell (Needs to be done manually: #183 ) with a valid column identifier

Expected behavior: A column is added
Observed behavior: The following error occurs Vizier-side
```
)
10:42:41.353 [qtp1268510462-74] ERROR mimir.api.MimirVizierServlet - MimirAPI POST ERROR: 
java.lang.Exception: Invalid view query : SELECT UNNAMED_COLUMN,NULL FOO FROM VIEW_1014954651; 
 Parsed.Failure(Position 1:22, found ",NULL FOO ")
        at mimir.MimirVizier$$anonfun$26.apply(MimirVizier.scala:563)
        at mimir.MimirVizier$$anonfun$26.apply(MimirVizier.scala:534)
        at mimir.MimirVizier$.logTime(MimirVizier.scala:1390)
        at mimir.MimirVizier$.createView(MimirVizier.scala:534)
        at mimir.api.CreateViewSRequest.handle(Request.scala:146)
        at mimir.api.MimirVizierServlet.doPost(MimirAPI.scala:110)
...
```

**Comment by okennedy** [comment]
Closed by https://github.com/UBOdin/mimir/commit/b5479c679980f2e258a87f28cb805a14fb7a1c77
