### ISSUE TITLE
Type issue in Vizual SET operation

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#2]
[Migrated from https://github.com/VizierDB/frontend/issues/11]

This looks like the implementation of SET isn't type-aware.

In https://demo.vizierdb.info/projects/07911f6f45df45cd9a1075ee2ec40a9f

```
[7] UPDATE pickone SET [3,2] = '2.5'

An error occurred while calling t.vistrailsQueryMimir.
: mimir.algebra.TypeException: Type Mismatch [CASE-WHEN]: found real, but expected varchar IF  (RID=2)  THEN '2.5' ELSE COL2 END
	at mimir.algebra.Typechecker$.assertLeastUpperBound(Typechecker.scala:313)
	at mimir.algebra.Typechecker.typeOf(Typechecker.scala:133)
	at mimir.algebra.Typechecker$$anonfun$schemaOf$1.apply(Typechecker.scala:179)
	at mimir.algebra.Typechecker$$anonfun$schemaOf$1.apply(Typechecker.scala:177)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mimir.algebra.Typechecker.schemaOf(Typechecker.scala:177)
	at mimir.algebra.Typechecker.schemaOf(Typechecker.scala:253)
	at mimir.algebra.Typechecker.schemaOf(Typechecker.scala:176)
	at mimir.algebra.Typechecker.schemaOf(Typechecker.scala:176)
	at mimir.exec.mode.BestGuess$.rewriteRaw(BestGuess.scala:46)
	at mimir.exec.mode.BestGuess$.rewrite(BestGuess.scala:116)
	at mimir.exec.mode.CompileMode.apply(CompileMode.scala:36)
	at mimir.Database.query(Database.scala:125)
	at mimir.Database.query(Database.scala:168)
	at mimir.MimirVizier$.operCSVResultsDeterminismAndExplanation(MimirVizier.scala:587)
	at mimir.MimirVizier$$anonfun$7.apply(MimirVizier.scala:290)
	at mimir.MimirVizier$$anonfun$7.apply(MimirVizier.scala:283)
	at mimir.MimirVizier$.time(MimirVizier.scala:655)
	at mimir.MimirVizier$.vistrailsQueryMimir(MimirVizier.scala:283)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by okennedy** [comment]
We should return to this discussion at some point.  A few more ideas:
- Add an annotation to cells that trigger a typecast (along the lines of what Mimir does)
- Schema-level annotations (once schema level uncertainty stabilizes in Mimir and migrates into Vizier)
