### ISSUE TITLE
LOAD DATASET fails when no load 'type' specified

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#77]
If you load a dataset without configuring a 'load format' (i.e., `Load Format = <none>`), it triggers a rather scary-looking error.

```
Py4JJavaError: An error occurred while calling t.loadCSV.
: java.lang.ClassNotFoundException: Failed to find data source: . Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:549)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:86)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:86)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:301)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156)
	at mimir.sql.SparkBackend.readDataSource(SparkBackend.scala:337)
	at mimir.util.LoadData$.handleLoadTableRaw(LoadData.scala:34)
	at mimir.Database.loadTable(Database.scala:550)
	at mimir.MimirVizier$$anonfun$9.apply(MimirVizier.scala:366)
	at mimir.MimirVizier$$anonfun$9.apply(MimirVizier.scala:334)
	at mimir.MimirVizier$.logTime(MimirVizier.scala:1196)
	at mimir.MimirVizier$.loadCSV(MimirVizier.scala:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: .DefaultSource
```

**Comment by mrb24** [comment]
closed by commit: https://github.com/VizierDB/web-api/commit/b37cb74b27def9228e33ecc9ce0416f7be122319
